"use client";
import { useEffect, useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";

type Incident={id:string;occurredAt:string;description:string;affectedContactCount:number;status:string;boardNotifiedAt:string|null;affectedPersonsNotifiedAt:string|null};
function remaining(deadline:number, now:number){const ms=deadline-now;if(ms<=0)return "Overdue";const hours=Math.ceil(ms/3_600_000);return `${Math.floor(hours/24)}d ${hours%24}h remaining`;}
export function BreachTracker({incidents}:{incidents:Incident[]}){const router=useRouter();const [clock,setClock]=useState(Date.now());const [error,setError]=useState("");useEffect(()=>{const id=setInterval(()=>setClock(Date.now()),60_000);return()=>clearInterval(id);},[]);
async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");const formElement=event.currentTarget;const form=new FormData(formElement);const response=await fetch("/api/incidents",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({occurredAt:new Date(String(form.get("occurredAt"))).toISOString(),description:form.get("description"),affectedContactCount:Number(form.get("count"))})});if(!response.ok){setError((await response.json()).error);return;}formElement.reset();router.refresh();}
async function update(id:string,field:"boardNotified"|"affectedPersonsNotified"){await fetch(`/api/incidents/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({[field]:true})});router.refresh();}
return <div className="stack"><form className="card stack" onSubmit={create}><h2>Log an incident</h2><div className="form-grid"><div className="field"><label>Occurred at</label><input name="occurredAt" type="datetime-local" required/></div><div className="field"><label>Affected-contact count</label><input name="count" type="number" min="0" required/></div></div><div className="field"><label>Description</label><textarea name="description" rows={3} required/></div>{error&&<p className="error">{error}</p>}<button className="btn">Create incident</button></form>{incidents.map(incident=>{const occurred=new Date(incident.occurredAt).getTime();const boardOver=!incident.boardNotifiedAt&&clock>occurred+72*3_600_000;const peopleOver=!incident.affectedPersonsNotifiedAt&&clock>occurred+144*3_600_000;return <article className="card stack" key={incident.id}><div><span className={`badge ${boardOver||peopleOver?"non_compliant":"at_risk"}`}>{boardOver||peopleOver?"✕ Deadline overdue":"▲ Active incident"}</span><h2>{incident.description}</h2><p className="muted small">Occurred {new Date(incident.occurredAt).toLocaleString("en-IN")} · {incident.affectedContactCount} contacts</p></div><div className={boardOver?"notice danger-note":"notice"}><strong>Board notification · 72 hours · statutory deadline</strong><br/>{incident.boardNotifiedAt?`✓ Logged ${new Date(incident.boardNotifiedAt).toLocaleString("en-IN")}`:remaining(occurred+72*3_600_000,clock)}{!incident.boardNotifiedAt&&<><br/><button className="btn secondary" onClick={()=>update(incident.id,"boardNotified")}>Log Board notification</button></>}</div><div className={peopleOver?"notice danger-note":"notice"}><strong>Affected-person notification · 144 hours</strong><br/><em>Internal escalation target, not a statutory deadline.</em> The Act uses “without delay” and sets no fixed statutory hour figure.<br/>{incident.affectedPersonsNotifiedAt?`✓ Logged ${new Date(incident.affectedPersonsNotifiedAt).toLocaleString("en-IN")}`:remaining(occurred+144*3_600_000,clock)}{!incident.affectedPersonsNotifiedAt&&<><br/><button className="btn secondary" onClick={()=>update(incident.id,"affectedPersonsNotified")}>Log affected-person notification</button></>}</div></article>})}</div>}
